# Generated by Django 4.2.27 on 2026-01-31 09:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_sleep', models.DateField(db_index=True, help_text='The date this sleep is logged for')),
                ('start_time', models.DateTimeField(help_text='When sleep started')),
                ('end_time', models.DateTimeField(help_text='When sleep ended')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Total time in bed (minutes)')),
                ('minutes_asleep', models.PositiveIntegerField(help_text='Actual sleep time (minutes)')),
                ('minutes_awake', models.PositiveIntegerField(default=0, help_text='Time awake during sleep (minutes)')),
                ('efficiency', models.PositiveIntegerField(blank=True, help_text='Sleep efficiency percentage', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('deep_sleep_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('light_sleep_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('rem_sleep_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('quality_rating', models.PositiveSmallIntegerField(blank=True, help_text="User's subjective quality rating (1-5)", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('sleep_type', models.CharField(choices=[('stages', 'Stages (detailed)'), ('classic', 'Classic')], default='classic', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('fitbit', 'Fitbit'), ('apple_health', 'Apple Health'), ('google_fit', 'Google Fit')], default='manual', max_length=20)),
                ('external_id', models.CharField(blank=True, help_text='ID from external source (e.g., Fitbit)', max_length=255)),
                ('is_main_sleep', models.BooleanField(default=True, help_text='Whether this is the main sleep period')),
                ('notes', models.TextField(blank=True, help_text='User notes about this sleep')),
                ('caffeine_intake', models.BooleanField(blank=True, null=True)),
                ('alcohol_intake', models.BooleanField(blank=True, null=True)),
                ('exercise_today', models.BooleanField(blank=True, null=True)),
                ('stress_level', models.PositiveSmallIntegerField(blank=True, help_text='Stress level (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sleep_records',
                'ordering': ['-date_of_sleep', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='SleepStageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('deep', 'Deep Sleep'), ('light', 'Light Sleep'), ('rem', 'REM Sleep'), ('wake', 'Awake'), ('restless', 'Restless'), ('asleep', 'Asleep')], max_length=20)),
                ('start_time', models.DateTimeField()),
                ('duration_seconds', models.PositiveIntegerField()),
                ('sleep_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_data', to='sleep.sleeprecord')),
            ],
            options={
                'db_table': 'sleep_stage_data',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='SleepGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_hours', models.DecimalField(decimal_places=1, default=8.0, max_digits=3, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(12)])),
                ('target_bedtime', models.TimeField(blank=True, null=True)),
                ('target_waketime', models.TimeField(blank=True, null=True)),
                ('min_sleep_hours_weekly', models.PositiveIntegerField(default=49, help_text='Minimum total sleep hours per week')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_goal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sleep_goals',
            },
        ),
        migrations.AddIndex(
            model_name='sleeprecord',
            index=models.Index(fields=['user', 'date_of_sleep'], name='sleep_recor_user_id_74f1c4_idx'),
        ),
        migrations.AddIndex(
            model_name='sleeprecord',
            index=models.Index(fields=['user', 'start_time'], name='sleep_recor_user_id_672d4c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sleeprecord',
            unique_together={('user', 'external_id')},
        ),
    ]
