# Generated by Django 4.2.27 on 2026-08-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sleeprecord',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='sleeprecord',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('user', 'external_id'), name='unique_user_external_id'),
        ),
    ]
