# Generated by Django 4.2.27 on 2026-01-31 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('hygiene', 'Sleep Hygiene'), ('routine', 'Bedtime Routine'), ('environment', 'Sleep Environment'), ('lifestyle', 'Lifestyle'), ('nutrition', 'Nutrition'), ('exercise', 'Exercise'), ('stress', 'Stress Management'), ('technology', 'Technology')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('short_tip', models.CharField(max_length=255)),
                ('min_sleep_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('max_sleep_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('min_efficiency', models.PositiveIntegerField(blank=True, null=True)),
                ('max_efficiency', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sleep_tips',
                'ordering': ['order', 'category'],
            },
        ),
        migrations.CreateModel(
            name='SleepInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('daily', 'Daily Summary'), ('weekly', 'Weekly Analysis'), ('monthly', 'Monthly Review'), ('pattern', 'Pattern Detection'), ('recommendation', 'Recommendation'), ('alert', 'Alert')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_helpful', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sleep_insights',
                'ordering': ['-created_at'],
            },
        ),
    ]
