# Generated by Django 4.2.7 on 2026-08-01 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_insights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsightJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('days', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('source', models.CharField(blank=True, choices=[('local_model', 'Local model'), ('rule_based', 'Rule based'), ('insufficient_data', 'Insufficient data')], max_length=20, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, choices=[('timeout', 'Timeout'), ('unreachable', 'Unreachable'), ('auth', 'Auth'), ('invalid_response', 'Invalid response'), ('internal', 'Internal')], max_length=20, null=True)),
                ('error_detail', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insight_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sleep_insight_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='sleep_insig_user_id_2005f2_idx')],
            },
        ),
    ]
