# Generated by Django 4.2.27 on 2026-09-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitbittoken',
            name='auto_sync',
            field=models.BooleanField(default=True, help_text='Include this user in the nightly scheduled sync.'),
        ),
        migrations.AddField(
            model_name='fitbittoken',
            name='consecutive_auth_failures',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
